import assert from 'node:assert/strict';
import {solve} from '../src/engine.js';
assert.equal(solve('1250 × 4').value,5000);
assert.equal(solve('1/3 + 1/6').answer,'1/2');
assert.equal(solve('1/3 - 1/6').answer,'1/6');
assert.equal(solve('-1/3 + 1/6').answer,'-1/6');
assert.equal(solve('sqrt(72) + sqrt(8)').answer,'8√2');
assert.equal(solve('sqrt(81)').value,9);
assert.equal(solve('cbrt(-27)').value,-3);
assert.equal(solve('log(100) + ln(e)').value,3);
assert.equal(solve('5!').value,120);
assert.ok(Math.abs(solve('sin(30)','DEG').value-.5)<1e-10);
assert.deepEqual(solve('x^2-5x+6=0').roots,[2,3]);
assert.deepEqual(solve('sqrt(x+5)=x-1').roots,[4]);
assert.deepEqual(solve('(x+1)/(x-2)=3').roots,[3.5]);
assert.deepEqual(solve('(x^2-1)/(x-1)=2').roots,[]);
assert.deepEqual(solve('2(x+3)=14').roots,[4]);
assert.deepEqual(solve('x^2+1=0').roots,[]);
assert.ok(solve('x^4-5x^2+4=0').roots.every((v,i)=>Math.abs(v-[-2,-1,1,2][i])<1e-8));
assert.equal(solve('x^4-5x^2+4=0').roots.length,4);
assert.throws(()=>solve('1/0'));
assert.throws(()=>solve('sqrt(-1)'));
assert.throws(()=>solve('1700!'));
assert.throws(()=>solve('import("test")'));
assert.throws(()=>solve('x=1=2'));
assert.throws(()=>solve('sin(x)=0'));
assert.throws(()=>solve('a=2'));
assert.throws(()=>solve('x^8=1'));
assert.equal(solve('4=5').answer,'Неверное равенство');
console.log('27 meaningful calculation and rejection checks passed');
