import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {pathToFileURL} from 'node:url';import {DatabaseSync} from 'node:sqlite';import ts from 'typescript';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(await fs.readFile('drizzle/0000_square_clint_barton.sql','utf8'));
globalThis.testEnv={DB:{prepare(sql){return{bind(...args){return{async first(){return sqlite.prepare(sql).get(...args)||null},async run(){return{meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}}}}}}}},BUCKET:{files:new Map(),async put(id,data,meta){this.files.set(id,{bytes:new Uint8Array(data),size:data.byteLength,...meta})},async head(id){return this.files.get(id)},async get(id,options){const o=this.files.get(id);if(!o)return null;const r=options?.range;return{body:r?o.bytes.slice(r.offset,r.offset+r.length):o.bytes}}}};
globalThis.testUser={userId:'a'};const dir=path.resolve('.test-runtime');await fs.mkdir(dir,{recursive:true});
async function load(name){let s=await fs.readFile(`app/api/${name}/route.ts`,'utf8');s=s.replace(/import\s*\{\s*env\s*\}\s*from\s*['"]cloudflare:workers['"];?/,`const env=globalThis.testEnv;`).replace(/import\s*\{\s*getChatGPTUser\s*\}\s*from\s*['"]@\/app\/chatgpt-auth['"];?/,`const getChatGPTUser=async()=>globalThis.testUser;`).replace(/(['"])@\/features\/media\/model\1/,JSON.stringify(pathToFileURL(path.resolve('features/media/model.ts')).href));const p=path.join(dir,name+'.mjs');await fs.writeFile(p,ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);return import(pathToFileURL(p).href)}
try{const library=await load('library'),assets=await load('assets');const json=(body,origin='https://media.test')=>new Request('https://media.test/api/library',{method:'PUT',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(body)});
const first=await(await library.GET()).json();assert.equal(first.revision,0);assert.equal(first.data.items.length,14);assert.equal((await library.PUT(json(first))).status,200);assert.equal((await library.PUT(json(first))).status,409);assert.equal((await library.PUT(json({...first,revision:1},'https://evil.test'))).status,403);assert.equal((await library.PUT(json({data:{version:1,items:[null],albums:[]},revision:1}))).status,400);
globalThis.testUser={userId:'b'};assert.equal((await(await library.GET()).json()).revision,0);globalThis.testUser={userId:'a'};assert.equal((await(await library.GET()).json()).revision,1);
const post=(type,body,origin='https://media.test')=>new Request('https://media.test/api/assets',{method:'POST',headers:{'Content-Type':type,Origin:origin},body});assert.equal((await assets.POST(post('image/svg+xml','<svg/>'))).status,400);assert.equal((await assets.POST(post('image/jpeg','abc','https://evil.test'))).status,403);assert.equal((await assets.POST(new Request('https://media.test/api/assets',{method:'POST',headers:{'Content-Type':'image/jpeg','Content-Length':'20000001'},body:'abc'}))).status,413);
const upload=await(await assets.POST(post('video/webm','0123456789'))).json();assert.ok(upload.url);const get=(range)=>new Request('https://media.test'+upload.url,{headers:range?{Range:range}:{}});assert.equal(await(await assets.GET(get())).text(),'0123456789');let response=await assets.GET(get('bytes=2-5'));assert.equal(response.status,206);assert.equal(response.headers.get('Content-Range'),'bytes 2-5/10');assert.equal(await response.text(),'2345');assert.equal(await(await assets.GET(get('bytes=-3'))).text(),'789');assert.equal((await assets.GET(get('bytes=10-'))).status,416);assert.equal((await assets.GET(get('bytes=0-2,3-4'))).status,416);
globalThis.testUser={userId:'b'};assert.equal((await assets.GET(get())).status,404);globalThis.testUser=null;assert.equal((await library.GET()).status,401);assert.equal((await assets.GET(get())).status,401);assert.equal((await assets.POST(post('image/jpeg','abc'))).status,401);
console.log('API: actual routes with SQLite, persisted revisions, conflicts, owner isolation, origins, upload limits and video Range requests passed.');
}finally{sqlite.close();await fs.rm(dir,{recursive:true,force:true})}
