import {getChatGPTUser} from '@/app/chatgpt-auth';
import {db,bucket,getFile,getShare,readBody,metadata,error,bounded,sameOrigin} from '@/lib/files-store';
import type {Row} from '@/lib/files-store';
import {validData,cleanName,QUOTA,withExtension} from '@/features/files/model';
const authenticated=async()=> (await getChatGPTUser())?.userId;
export async function GET(req:Request){const owner=await authenticated();if(!owner)return error('Войдите в приложение',401);try{const q=new URL(req.url).searchParams;
 if(q.has('shares'))return Response.json((await db().prepare('SELECT token,file,name,editable FROM shares WHERE owner=? ORDER BY created DESC').bind(owner).all()).results.map((s:any)=>({...s,editable:!!s.editable})));
 if(q.has('id')){const token=q.get('token');const share=token?await getShare(token):null;if(token&&!share)return error('Ссылка отозвана или не существует',404);
 const row=await getFile(share?.file||q.get('id')!,share?undefined:owner);if(!row||row.trashed)return error('Файл не найден',404);
 const data=await readBody(share&&!share.editable?share.blob!:row.blob);
 return Response.json({file:share&&!share.editable?{...metadata(row),name:share.name,kind:share.kind}:metadata(row),data,editable:share?!!share.editable:true,shared:!!share});}
 const [f,d]=await Promise.all([db().prepare('SELECT * FROM files WHERE owner=? ORDER BY updated DESC').bind(owner).all<Row>(),db().prepare('SELECT id,name FROM folders WHERE owner=?').bind(owner).all()]);return Response.json({files:f.results.map(metadata),folders:d.results,used:f.results.reduce((s,r)=>s+r.size,0),quota:QUOTA});
 }catch(e){console.error(e);return error('Облако временно недоступно. Попробуйте ещё раз.',503);}}
export async function POST(req:Request){const owner=await authenticated();if(!owner)return error('Войдите в приложение',401);if(!sameOrigin(req))return error('Запрос отклонён',403);try{const b=await bounded(req);
 if(b.op==='folder'){if(b.id){const f=await db().prepare('SELECT id FROM folders WHERE id=? AND owner=?').bind(b.id,owner).first();if(!f)return error('Папка не найдена',404);if(b.remove){await db().batch([db().prepare('UPDATE files SET folder=NULL WHERE folder=? AND owner=?').bind(b.id,owner),db().prepare('DELETE FROM folders WHERE id=? AND owner=?').bind(b.id,owner)]);return Response.json({id:b.id,name:''});}}
 const name=typeof b.name==='string'?b.name.trim().slice(0,150):'';if(!name)return error('Введите название папки');const id=b.id||crypto.randomUUID();await db().prepare('INSERT INTO folders(id,owner,name) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name WHERE folders.owner=?').bind(id,owner,name,owner).run();return Response.json({id,name});}
 if(b.op==='share'){const row=await getFile(b.id,owner);if(!row||row.trashed)return error('Файл не найден',404);const token=crypto.randomUUID(),editable=b.editable===true;let key:null|string=null;if(!editable){key='shares/'+owner+'/'+token;await bucket().put(key,JSON.stringify(await readBody(row.blob)));}
 await db().prepare('INSERT INTO shares(token,owner,file,name,kind,editable,blob,created) VALUES(?,?,?,?,?,?,?,?)').bind(token,owner,row.id,row.name,row.kind,editable?1:0,key,Date.now()).run();return Response.json({token});}
 if(b.op!=='receive'||!['txt','prsn'].includes(b.kind)||!validData(b.kind,b.data))return error('Поддерживаются только текстовые .txt и .prsn');
 if(b.folder&&!await db().prepare('SELECT id FROM folders WHERE id=? AND owner=?').bind(b.folder,owner).first())return error('Папка не найдена');
 const name=cleanName(typeof b.name==='string'?b.name:'',b.kind),body=JSON.stringify(b.data),size=new TextEncoder().encode(body).length;
 const totals=await db().prepare('SELECT COALESCE(SUM(size),0) as used,COUNT(*) as count FROM files WHERE owner=?').bind(owner).first<{used:number;count:number}>();if((totals?.used||0)+size>QUOTA||(totals?.count||0)>=2000)return error('Недостаточно места в облаке',413);
 const id=crypto.randomUUID(),key='files/'+owner+'/'+id+'/'+crypto.randomUUID();await bucket().put(key,body);const updated=Date.now();await db().prepare('INSERT INTO files(id,owner,name,kind,folder,downloaded,updated,revision,size,blob) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,owner,name,b.kind,b.folder||null,1,updated,1,size,key).run();return Response.json({file:metadata((await getFile(id,owner))!),data:b.data,editable:true});
 }catch(e){console.error(e);return error('Не удалось выполнить действие. Проверьте файл и повторите.',503);}}
export async function PUT(req:Request){const owner=await authenticated();if(!owner)return error('Войдите в приложение',401);if(!sameOrigin(req))return error('Запрос отклонён',403);try{const b=await bounded(req);const share=b.token?await getShare(b.token):null;if(b.token&&(!share||!share.editable))return error('Редактирование запрещено владельцем',403);const row=await getFile(share?.file||b.id,share?undefined:owner);if(!row||row.trashed)return error('Файл не найден',404);
 if(!validData(row.kind,b.data)||!Number.isInteger(b.revision))return error('Некорректное содержимое');if(b.revision!==row.revision)return error('Файл изменился в другой вкладке. Скопируйте свой текст перед обновлением.',409);
 const body=JSON.stringify(b.data),size=new TextEncoder().encode(body).length;const sum=await db().prepare('SELECT COALESCE(SUM(size),0) as used FROM files WHERE owner=?').bind(row.owner).first<{used:number}>();if((sum?.used||0)-row.size+size>QUOTA)return error('Недостаточно места в облаке',413);
 const key='files/'+row.owner+'/'+row.id+'/'+crypto.randomUUID();await bucket().put(key,body);const r=await db().prepare('UPDATE files SET blob=?,size=?,updated=?,revision=revision+1 WHERE id=? AND revision=?').bind(key,size,Date.now(),row.id,b.revision).run();if(!r.meta.changes){await bucket().delete(key);return error('Другой пользователь уже сохранил изменения. Скопируйте свой текст перед обновлением.',409);}await bucket().delete(row.blob);return Response.json({file:metadata((await getFile(row.id))!),data:b.data,editable:true,shared:!!share});
 }catch(e){console.error(e);return error('Не удалось сохранить. Ваш текст остаётся в редакторе.',503);}}
export async function PATCH(req:Request){const owner=await authenticated();if(!owner)return error('Войдите в приложение',401);if(!sameOrigin(req))return error('Запрос отклонён',403);try{const {id,changes:c}=await bounded(req);const row=await getFile(id,owner);if(!row)return error('Файл не найден',404);if(c.folder&& !await db().prepare('SELECT id FROM folders WHERE owner=? AND id=?').bind(owner,c.folder).first())return error('Папка не найдена');
 await db().prepare('UPDATE files SET name=?,folder=?,favorite=?,trashed=?,downloaded=? WHERE id=? AND owner=?').bind(typeof c.name==='string'?withExtension(c.name,row.name,row.kind):row.name,c.folder===null?null:c.folder||row.folder,typeof c.favorite==='boolean'?+c.favorite:row.favorite,typeof c.trashed==='boolean'?+c.trashed:row.trashed,typeof c.downloaded==='boolean'?+c.downloaded:row.downloaded,id,owner).run();return Response.json(metadata((await getFile(id,owner))!));}catch(e){console.error(e);return error('Не удалось обновить файл',503);}}
export async function DELETE(req:Request){const owner=await authenticated();if(!owner)return error('Войдите в приложение',401);if(!sameOrigin(req))return error('Запрос отклонён',403);try{const b=await bounded(req);const s=await db().prepare('SELECT blob FROM shares WHERE token=? AND owner=?').bind(b.token,owner).first<{blob:string|null}>();await db().prepare('DELETE FROM shares WHERE token=? AND owner=?').bind(b.token,owner).run();if(s?.blob)await bucket().delete(s.blob);return Response.json({ok:true});}catch{return error('Не удалось отозвать ссылку',503);}}
