import {create,all} from 'mathjs';
const math=create(all,{number:'number'});
const allowedFunctions=new Set(['sqrt','cbrt','nthRoot','sin','cos','tan','asin','acos','atan','log','ln','abs','exp','factorial']);
const fnNames={sqrt:'Вычисляем квадратный корень',cbrt:'Вычисляем кубический корень',nthRoot:'Вычисляем корень',sin:'Вычисляем синус',cos:'Вычисляем косинус',tan:'Вычисляем тангенс',log:'Вычисляем логарифм',ln:'Вычисляем натуральный логарифм',abs:'Находим модуль',factorial:'Вычисляем факториал',exp:'Вычисляем экспоненту'};
export function normalize(input){return input.trim().replace(/[−–—]/g,'-').replace(/[×·⋅]/g,'*').replace(/÷/g,'/').replace(/,/g,'.').replace(/π/g,'pi').replace(/²/g,'^2').replace(/³/g,'^3').replace(/⁴/g,'^4').replace(/√\s*\(/g,'sqrt(').replace(/√\s*(\d+(?:\.\d+)?)/g,'sqrt($1)').replace(/∛\s*\(/g,'cbrt(').replace(/\bln\s*\(/g,'ln(').replace(/(\d)\s+(?=\d{3}(?:\D|$))/g,'$1').replace(/([0-9])\s*x\b/g,'$1*x');}
export const fmt=(v)=>{if(!Number.isFinite(v))throw new Error('Результат не определён в действительных числах.');return math.format(Math.abs(v)<1e-12?0:v,{precision:12}).replace(/\./g,',');};
const texNumber=v=>fmt(v).replace(/,/g,'{,}');
export function parsePart(s){const n=math.parse(s);let count=0;n.traverse(node=>{if(++count>160)throw new Error('Выражение слишком длинное.');if(node.isConstantNode){if(typeof node.value!=='number')throw new Error('Допустимы только числа и математические символы.');}else if(node.isSymbolNode){if(!['x','pi','e',...allowedFunctions].includes(node.name))throw new Error('Используйте только переменную x.');}else if(node.isFunctionNode){if(!allowedFunctions.has(node.fn.name))throw new Error('Эта функция пока не поддерживается.');}else if(node.isOperatorNode){if(!['+','-','*','/','^','!','%'].includes(node.op))throw new Error('Этот оператор пока не поддерживается.');}else if(!node.isParenthesisNode){throw new Error('Введите выражение, а не команду.');}});return n;}
export function evaluateNode(node,angle='RAD',x){if(node.isParenthesisNode)return evaluateNode(node.content,angle,x);if(node.isConstantNode)return node.value;if(node.isSymbolNode){if(node.name==='pi')return Math.PI;if(node.name==='e')return Math.E;if(node.name==='x'&&x!==undefined)return x;throw new Error('Для выражения с x введите уравнение со знаком =.');}const args=node.args.map(n=>evaluateNode(n,angle,x));let v;if(node.isOperatorNode){const[a,b]=args;switch(node.op){case '+':v=b===undefined?a:a+b;break;case '-':v=b===undefined?-a:a-b;break;case '*':v=a*b;break;case '/':if(b===0)throw new Error('На ноль делить нельзя.');v=a/b;break;case '^':if(Math.abs(b)>10000)throw new Error('Слишком большая степень.');v=Math.pow(a,b);break;case '!':if(!Number.isInteger(a)||a<0||a>170)throw new Error('Факториал доступен для целых чисел от 0 до 170.');v=math.factorial(a);break;case '%':if(b===0)throw new Error('На ноль делить нельзя.');v=b===undefined?a/100:a%b;break;}}else{const name=node.fn.name;let a=args[0];if(['sin','cos','tan'].includes(name)&&angle==='DEG')a=a*Math.PI/180;switch(name){case 'sqrt':v=Math.sqrt(a);break;case 'cbrt':v=Math.cbrt(a);break;case 'nthRoot':if(!args[1]||!Number.isInteger(args[1]))throw new Error('Степень корня должна быть ненулевым целым числом.');v=a<0&&args[1]%2? -Math.pow(-a,1/args[1]):Math.pow(a,1/args[1]);break;case 'log':v=args[1]!==undefined?Math.log(a)/Math.log(args[1]):Math.log10(a);break;case 'ln':v=Math.log(a);break;case 'factorial':if(!Number.isInteger(a)||a<0||a>170)throw new Error('Факториал доступен для целых чисел от 0 до 170.');v=math.factorial(a);break;default:v=Math[name](a);if(['asin','acos','atan'].includes(name)&&angle==='DEG')v*=180/Math.PI;}}if(!Number.isFinite(v))throw new Error('Результат не определён в действительных числах.');return v;}
export function toTex(s){try{return parsePart(normalize(s)).toTex({parenthesis:'keep',implicit:'hide'});}catch{return '';}}
const hasX=n=>{let yes=false;n.traverse(v=>{if(v.isSymbolNode&&v.name==='x')yes=true;});return yes;};
function exact(n){if(n.isParenthesisNode)return exact(n.content);if(n.isConstantNode)return math.fraction(n.value);if(n.isOperatorNode){const a=exact(n.args[0]),b=n.args[1]?exact(n.args[1]):null;switch(n.op){case '+':return b?math.add(a,b):a;case '-':return b?math.subtract(a,b):math.unaryMinus(a);case '*':return math.multiply(a,b);case '/':if(Number(b)===0)throw Error();return math.divide(a,b);case '^':if(!Number.isInteger(Number(b))||Math.abs(Number(b))>40)throw Error();return math.pow(a,Number(b));}}if(n.isFunctionNode&&['sqrt','cbrt'].includes(n.fn.name)){const f=exact(n.args[0]);const root=n.fn.name==='sqrt'?Math.sqrt:Math.cbrt;const num=root(Number(f.n)),den=root(Number(f.d));if(!Number.isInteger(num)||!Number.isInteger(den)||f.s<0&&n.fn.name==='sqrt')throw Error();return math.fraction(num*f.s,den);}throw Error();}
const fractionText=f=>f.d===1n?`${f.s<0?'-':''}${f.n}`:`${f.s<0?'-':''}${f.n}/${f.d}`;
const fractionTex=f=>f.d===1n?fractionText(f):`${f.s<0?'-':''}\\frac{${f.n}}{${f.d}}`;
function numericSteps(n,angle,steps){if(n.isParenthesisNode)return numericSteps(n.content,angle,steps);if(!n.args)return;for(const arg of n.args)numericSteps(arg,angle,steps);const val=evaluateNode(n,angle);let title=n.isFunctionNode?fnNames[n.fn.name]||'Вычисляем функцию':({'/':'Выполняем деление','^':'Возводим в степень','*':'Выполняем умножение','+':'Складываем','-':'Вычитаем','!':'Вычисляем факториал','%':'Находим один процент'}[n.op]||'Вычисляем');let exactVal;try{exactVal=exact(n);}catch{}if(n.isOperatorNode&&['+','-'].includes(n.op)&&n.args.length===2){try{const a=exact(n.args[0]),b=exact(n.args[1]);if(a.d!==1n||b.d!==1n){const gcd=(a,b)=>b?gcd(b,a%b):a;const d=a.d*b.d/gcd(a.d,b.d);steps.push({title:'Приводим дроби к общему знаменателю',tex:`\\frac{${BigInt(a.s)*a.n*(d/a.d)}}{${d}} ${n.op} \\frac{${BigInt(b.s)*b.n*(d/b.d)}}{${d}}`});title='Складываем числители и сокращаем дробь';}}catch{}}steps.push({title,tex:`${n.toTex({parenthesis:'keep',implicit:'hide'})} ${exactVal?'=':'\\approx'} ${exactVal?fractionTex(exactVal):texNumber(val)}`});}
const trim=a=>{while(a.length>1&&Math.abs(a[a.length-1])<1e-12)a.pop();return a;};
const add=(a,b,sign=1)=>trim(Array.from({length:Math.max(a.length,b.length)},(_,i)=>(a[i]||0)+sign*(b[i]||0)));
const mul=(a,b)=>{if(a.length+b.length>15)throw new Error('Поддерживаются уравнения до 6-й степени.');const r=Array(a.length+b.length-1).fill(0);a.forEach((v,i)=>b.forEach((w,j)=>r[i+j]+=v*w));return trim(r);};
const pow=(a,p)=>{let r=[1];for(let i=0;i<p;i++)r=mul(r,a);return r;};
function rational(n,angle){if(!hasX(n))return{n:[evaluateNode(n,angle)],d:[1]};if(n.isParenthesisNode)return rational(n.content,angle);if(n.isSymbolNode&&n.name==='x')return{n:[0,1],d:[1]};if(!n.isOperatorNode)throw new Error('Этот вид уравнения пока не поддерживается. Попробуйте линейное, квадратное, рациональное или уравнение с изолированным корнем.');const a=rational(n.args[0],angle);if(n.args.length===1)return{n:n.op==='-'?a.n.map(v=>-v):a.n,d:a.d};const b=rational(n.args[1],angle);switch(n.op){case '+':case '-':return{n:add(mul(a.n,b.d),mul(b.n,a.d),n.op==='-'?-1:1),d:mul(a.d,b.d)};case '*':return{n:mul(a.n,b.n),d:mul(a.d,b.d)};case '/':return{n:mul(a.n,b.d),d:mul(a.d,b.n)};case '^':{if(hasX(n.args[1]))throw new Error('Переменная в степени пока не поддерживается.');const p=evaluateNode(n.args[1],angle);if(!Number.isInteger(p)||Math.abs(p)>6)throw new Error('Для уравнения используйте целую степень от −6 до 6.');return p>=0?{n:pow(a.n,p),d:pow(a.d,p)}:{n:pow(a.d,-p),d:pow(a.n,-p)};}default:throw new Error('Этот вид уравнения пока не поддерживается.');}}
const polyText=a=>{let s='';for(let i=a.length-1;i>=0;i--){if(Math.abs(a[i])<1e-12)continue;let c=Math.abs(a[i]);s+=(s?(a[i]<0?' − ':' + '):(a[i]<0?'−':''))+(i&&Math.abs(c-1)<1e-12?'':fmt(c))+(i?'x'+(i>1?'^'+i:''):'');}return s||'0';};
const peval=(a,x)=>a.reduceRight((acc,v)=>acc*x+v,0);
function polynomialRoots(a){a=trim([...a]);if(a.length===1)return[];if(a.length===2)return[-a[0]/a[1]];const bound=1+Math.max(...a.slice(0,-1).map(v=>Math.abs(v/a.at(-1))));const critical=polynomialRoots(a.slice(1).map((v,i)=>v*(i+1))).filter(x=>x>-bound&&x<bound);const pts=[-bound,...critical,bound].sort((a,b)=>a-b),roots=[];for(const x of critical){if(Math.abs(peval(a,x))<1e-8)roots.push(x);}for(let i=0;i<pts.length-1;i++){let l=pts[i],r=pts[i+1];if(peval(a,l)*peval(a,r)>=0)continue;for(let j=0;j<110;j++){const m=(l+r)/2;if(peval(a,l)*peval(a,m)<=0)r=m;else l=m;}roots.push((l+r)/2);}return roots.sort((a,b)=>a-b).filter((v,i,r)=>!i||Math.abs(v-r[i-1])>1e-7);}
const unwrap=n=>n.isParenthesisNode?unwrap(n.content):n;

function surd(n){if(n.isParenthesisNode)return surd(n.content);if(n.isConstantNode)return{c:n.value,r:1};if(n.isFunctionNode&&n.fn.name==='sqrt'){const v=evaluateNode(n.args[0]);if(!Number.isInteger(v)||v<0||v>1000000)throw Error();let c=1,r=v;for(let i=2;i*i<=r;i++){while(r%(i*i)===0){c*=i;r/=i*i;}}return{c,r};}if(n.isOperatorNode){const a=surd(n.args[0]);if(n.args.length===1)return{c:n.op==='-'?-a.c:a.c,r:a.r};const b=surd(n.args[1]);if(['+','-'].includes(n.op)&&a.r===b.r)return{c:a.c+(n.op==='+'?1:-1)*b.c,r:a.r};if(n.op==='*'){if(a.r===b.r)return{c:a.c*b.c*a.r,r:1};if(a.r===1||b.r===1)return{c:a.c*b.c,r:a.r===1?b.r:a.r};}if(n.op==='/'){if(a.r===b.r&&b.c)return{c:a.c/b.c,r:1};if(b.r===1&&b.c)return{c:a.c/b.c,r:a.r};}}throw Error();}

export function solve(input,angle='RAD'){if(typeof input!=='string'||input.length>500||!input.trim())throw new Error('Введите выражение или уравнение.');const s=normalize(input);const pieces=s.split('=');if(pieces.length>2)throw new Error('Введите одно уравнение с одним знаком =.');const steps=[];if(pieces.length===1){const n=parsePart(s);const val=evaluateNode(n,angle);numericSteps(n,angle,steps);let f;try{f=exact(n);}catch{}let radicalForm;try{radicalForm=surd(n);if(radicalForm.r===1||radicalForm.r===0)radicalForm=null;}catch{}const result=radicalForm?`${fmt(radicalForm.c)}√${radicalForm.r}`:f?fractionText(f):fmt(val);if(radicalForm)steps.push({title:'Выносим квадратные множители и собираем подобные корни',tex:`${n.toTex()}=${texNumber(radicalForm.c)}\\sqrt{${radicalForm.r}}`});const detail=radicalForm?`≈ ${fmt(val)}`:f&&f.d!==1n?`≈ ${fmt(val)}`:!f?'Приближённое значение':'';return{kind:'expression',input,answer:result,value:val,detail,steps:steps.length?steps:[{title:'Исходное значение',tex:n.toTex()}],resultTex:radicalForm?`${texNumber(radicalForm.c)}\\sqrt{${radicalForm.r}}`:f?fractionTex(f):texNumber(val)};}
const left=parsePart(pieces[0]),right=parsePart(pieces[1]);if(!hasX(left)&&!hasX(right)){const l=evaluateNode(left,angle),r=evaluateNode(right,angle);return{kind:'equality',input,answer:Math.abs(l-r)<1e-10?'Верное равенство':'Неверное равенство',detail:'',steps:[{title:'Вычисляем левую и правую части',tex:`${texNumber(l)} ${Math.abs(l-r)<1e-10?'=':'\\ne'} ${texNumber(r)}`}],roots:[]};}
steps.push({title:'Исходное уравнение',tex:`${left.toTex({implicit:'hide'})} = ${right.toTex({implicit:'hide'})}`});let a,b,radical=false;let l=unwrap(left),r=unwrap(right);if((l.isFunctionNode&&l.fn.name==='sqrt'&&hasX(l))||(r.isFunctionNode&&r.fn.name==='sqrt'&&hasX(r))){if(!(l.isFunctionNode&&l.fn.name==='sqrt'))[l,r]=[r,l];if(hasX(r)&&r.isFunctionNode)throw new Error('Два переменных корня пока не поддерживаются.');a=rational(l.args[0],angle);b=rational(r,angle);b={n:mul(b.n,b.n),d:mul(b.d,b.d)};radical=true;steps.push({title:'Область допустимых значений',tex:`${l.args[0].toTex()} \\ge 0,\\quad ${r.toTex()} \\ge 0`});steps.push({title:'Возводим обе части в квадрат',tex:`${l.args[0].toTex()} = \\left(${r.toTex()}\\right)^2`});}else{a=rational(left,angle);b=rational(right,angle);}
if(a.d.length>1||b.d.length>1){steps.push({title:'Знаменатели не должны равняться нулю',tex:`${toTex(polyText(a.d))} \\ne 0,\\quad ${toTex(polyText(b.d))} \\ne 0`});steps.push({title:'Умножаем обе части на общий знаменатель',tex:`(${toTex(polyText(a.n))})(${toTex(polyText(b.d))})=(${toTex(polyText(b.n))})(${toTex(polyText(a.d))})`});}
const p=add(mul(a.n,b.d),mul(b.n,a.d),-1);if(p.length>7)throw new Error('Поддерживаются полиномы до 6-й степени.');steps.push({title:'Раскрываем скобки и собираем подобные',tex:`${toTex(polyText(p))}=0`});let candidates=[],detail='';if(p.length===1){if(Math.abs(p[0])<1e-12)return{kind:'equation',input,answer:'Любое допустимое x',detail:'С учётом ОДЗ исходного уравнения.',steps,roots:[]};return{kind:'equation',input,answer:'Нет решений',detail:'Получено противоречие.',steps,roots:[]};}
if(p.length===2){const x=-p[0]/p[1];candidates=[x];steps.push({title:'Переносим свободный член и делим на коэффициент',tex:`x=\\frac{${texNumber(-p[0])}}{${texNumber(p[1])}}=${texNumber(x)}`});}else if(p.length===3){const[c,b,a]=p,D=b*b-4*a*c;steps.push({title:'Находим дискриминант',tex:`D=b^2-4ac=(${texNumber(b)})^2-4\\cdot(${texNumber(a)})\\cdot(${texNumber(c)})=${texNumber(D)}`});if(D<-1e-10){steps.push({title:'Дискриминант отрицательный',tex:'D<0'});return{kind:'equation',input,answer:'Нет действительных корней',detail:'Комплексные числа пока не поддерживаются.',steps,roots:[]};}const rt=Math.sqrt(Math.max(0,D));candidates=[(-b-rt)/(2*a),(-b+rt)/(2*a)].filter((x,i,a)=>!i||Math.abs(x-a[0])>1e-10);steps.push({title:'Применяем формулу корней',tex:`x_{1,2}=\\frac{-b\\pm\\sqrt{D}}{2a}=\\frac{${texNumber(-b)}\\pm\\sqrt{${texNumber(Math.max(0,D))}}}{${texNumber(2*a)}}`});if(!Number.isInteger(rt))detail='Корни показаны приближённо.';}else{candidates=polynomialRoots(p);detail='Действительные корни найдены численно; значения приближённые.';steps.push({title:'Ограничиваем область поиска корней',tex:`|x|\\le 1+\\max_{k<n}\\left|\\frac{a_k}{a_n}\\right|`});steps.push({title:'Разделяем интервалы критическими точками',tex:`P'(x)=${toTex(polyText(p.slice(1).map((v,i)=>v*(i+1))))}`});steps.push({title:'Уточняем корни методом деления интервала пополам',tex:candidates.length?candidates.map((v,i)=>`x_{${i+1}}\\approx${texNumber(v)}`).join(',\\quad '):'\\text{Действительные корни не найдены}'});}
const roots=candidates.filter(x=>{try{const lv=evaluateNode(left,angle,x),rv=evaluateNode(right,angle,x);return Math.abs(lv-rv)<=1e-7*Math.max(1,Math.abs(lv),Math.abs(rv));}catch{return false;}});if(roots.length){for(const x of roots){const lv=evaluateNode(left,angle,x),rv=evaluateNode(right,angle,x);steps.push({title:`Проверяем подстановкой x = ${fmt(x)}`,tex:`${texNumber(lv)} \\approx ${texNumber(rv)}`});}}if(roots.length<candidates.length){steps.push({title:'Исключаем посторонние корни',tex:'\\text{Оставляем только корни исходного уравнения}'});}return{kind:'equation',input,answer:roots.length?roots.map((x,i)=>`${roots.length>1?'x'+(i+1):'x'} = ${fmt(x)}`).join('; '):'Нет действительных решений',detail:detail||(radical?'Проверено в исходном уравнении.':'Корни проверены подстановкой.'),steps,roots,resultTex:roots.map((x,i)=>`x${roots.length>1?'_{'+(i+1)+'}':''}=${texNumber(x)}`).join(',\\quad ')};}
