// VOIDEX adapter of the Calculator: the logic of the original src/main.js,
// mounted into a VOIDEX window instead of a standalone page.
//
// What changed compared to main.js (and why):
// • elements are looked up inside the window root, not the whole document;
//   the scientific / embedded flags live on the root, not on <body>;
// • keyboard input is handled while focus is inside the window (main.js
//   listened on the whole document, which would steal keys from other apps);
// • dialogs open inside the window (scrim + panel) instead of page-modal;
// • OCR assets come from the VOIDEX origin (ocrBase), still 100 % on device;
// • layout "fit" levels keep everything on screen without page scroll;
// • every listener, timer and the OCR worker are released on destroy().
// The maths (engine.js), the keypad, the step-by-step solution, history,
// photo / crop / OCR flow and all texts are the original ones.
import 'katex/dist/katex.min.css';
import './calculator.css';
import katex from 'katex';
import {solve,toTex,normalize} from '../engine.js';
import {markup} from './markup.js';

// History lives as long as the page (as in the original: "until the page is closed"),
// so closing and reopening the Calculator window keeps it.
let history=[];

export function mountCalculator(root,{ocrBase='/apps/calculator/ocr/',onSolutionToggle}={}){
const ac=new AbortController();const on=(el,type,fn,opts)=>el.addEventListener(type,fn,{...opts,signal:ac.signal});
root.classList.add('vxc');root.innerHTML=markup;root.tabIndex=-1;
const $=id=>root.querySelector('#vxc-'+id);let science=false,angle='RAD',result=null,done=false,destroyed=false;const expression=$('expression');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function mathHTML(tex){return katex.renderToString(tex,{throwOnError:false,strict:false,trust:false});}
let toastTimer;function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2600);}
function preview(){const s=expression.value;const parts=s.split('=');const tex=parts.map(toTex);$('mathPreview').innerHTML=science&&tex.every(Boolean)&&s.trim()?mathHTML(tex.join(' = ')):'';expression.style.height='auto';expression.style.height=Math.min(105,expression.scrollHeight)+'px';}
function setMode(isScience){const changed=science!==isScience;science=isScience;root.classList.toggle('science',science);$('basicMode').classList.toggle('selected',!science);$('scienceMode').classList.toggle('selected',science);$('basicMode').setAttribute('aria-selected',!science);$('scienceMode').setAttribute('aria-selected',science);$('scientificTools').hidden=!science;$('photoActions').hidden=!science;$('modeLabel').textContent=science?'НАУЧНЫЙ РЕЖИМ':'ОБЫЧНЫЙ РЕЖИМ';$('footerStatus').textContent=science?'Научный режим · '+angle:'Обычный режим';const eq=root.querySelector('[data-key=solve]');eq.textContent=science?'Решить':'=';eq.classList.toggle('science-equals',science);preview();fit();if(changed)animateMode();}
// Step 2.8: switching modes eases the new keys in instead of swapping them at once.
function animateMode(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(const id of ['scientificTools','keypad','photoActions']){const el=$(id);if(!el||el.hidden||!el.animate)continue;el.animate([{opacity:0,transform:'translateY(10px) scale(.985)'},{opacity:1,transform:'none'}],{duration:320,easing:'cubic-bezier(.22,1,.36,1)'});}const label=$('modeLabel');if(label&&label.animate)label.animate([{opacity:0},{opacity:1}],{duration:240,easing:'ease-out'});}
$('basicMode').onclick=()=>setMode(false);$('scienceMode').onclick=()=>setMode(true);$('angleMode').onclick=()=>{angle=angle==='RAD'?'DEG':'RAD';$('angleMode').textContent=angle;setMode(science);invalidate();};
function invalidate(){done=false;result=null;$('answer').textContent='…';$('answerDetail').textContent='Нажмите '+(science?'«Решить»':'«=»');$('steps').innerHTML='<div class="empty-solution">Введите выражение и нажмите '+(science?'«Решить»':'«=»')+'. Здесь появится последовательность вычислений.</div>';preview();}
function insert(text,selectOffset){if(done&&result?.kind==='expression'&&/^[+−\-×÷*/^]/.test(text)){expression.value=String(result.value);expression.setSelectionRange(expression.value.length,expression.value.length);}if(done&&/^[0-9.(a-z]/i.test(text)&&!['x','e','pi'].includes(text)){expression.value='';}done=false;const start=expression.selectionStart??expression.value.length,end=expression.selectionEnd??start;expression.value=expression.value.slice(0,start)+text+expression.value.slice(end);const pos=start+text.length+(selectOffset||0);expression.setSelectionRange(Math.max(start,pos),Math.max(start,pos));invalidate();}
function action(key){if(key==='clear'){expression.value='';invalidate();$('answer').textContent='0';$('answerDetail').textContent='';return;}if(key==='solve'){calculate();return;}if(key==='back'){if(done)done=false;const a=expression.selectionStart,b=expression.selectionEnd;expression.value=expression.value.slice(0,a===b?Math.max(0,a-1):a)+expression.value.slice(b);expression.setSelectionRange(Math.max(0,a-1),Math.max(0,a-1));invalidate();return;}if(key==='sign'){const value=expression.value.trim();expression.value=value.startsWith('-(')&&value.endsWith(')')?value.slice(2,-1):value?'-('+value+')':'-';expression.setSelectionRange(expression.value.length,expression.value.length);invalidate();return;}if(key==='percent'){insert('/100');return;}insert(key);}
const keys=[['AC','clear','function'],['±','sign','function'],['%','percent','function'],['÷','÷','operator'],['7','7',''],['8','8',''],['9','9',''],['×','×','operator'],['4','4',''],['5','5',''],['6','6',''],['−','−','operator'],['1','1',''],['2','2',''],['3','3',''],['+','+','operator'],['0','0','zero'],[',',',',''],['=','solve','equals']];for(const[label,key,cls]of keys){const b=document.createElement('button');b.className='key '+cls;b.textContent=label;b.dataset.key=key;b.setAttribute('aria-label',key==='solve'?'Вычислить':key==='clear'?'Очистить выражение':key==='sign'?'Изменить знак':label);b.onpointerdown=e=>e.preventDefault();b.onclick=()=>action(key);$('keypad').append(b);}
const scientific=[['a/b','()/()',-4],['√','sqrt()',-1],['∛','cbrt()',-1],['x²','^2',0],['xʸ','^',0],['x','x',0],['sin','sin()',-1],['cos','cos()',-1],['tan','tan()',-1],['log','log()',-1],['ln','ln()',-1],['π','pi',0],['(','(',0],[')',')',0],['|x|','abs()',-1],['n!','!',0],['e','e',0],['=','= ',0]];for(const[label,value,offset]of scientific){const b=document.createElement('button');b.className='science-key';b.textContent=label;b.dataset.science=label;b.setAttribute('aria-label',label==='a/b'?'Вставить дробь':label==='√'?'Квадратный корень':label);b.onpointerdown=e=>e.preventDefault();b.onclick=()=>{insert(value,offset);if(offset){expression.focus({preventScroll:true});}};$('scienceKeys').append(b);}
// Tabbed science layout (short windows): the functions tab gets its own "Решить" key.
{const b=document.createElement('button');b.className='science-key solve-key';b.textContent='Решить';b.setAttribute('aria-label','Вычислить');b.setAttribute('data-testid','calc-solve-fn');b.onpointerdown=e=>e.preventDefault();b.onclick=()=>calculate();$('scienceKeys').append(b);}
$('backspace').onclick=()=>action('back');expression.oninput=()=>invalidate();on(expression,'keydown',e=>{if(e.key==='Enter'){e.preventDefault();calculate();}if(e.key==='Escape'){e.preventDefault();action('clear');}});
on(root,'keydown',e=>{if(e.key==='Escape'&&root.querySelector('dialog[open]')){e.preventDefault();closeDialogs();return;}if(root.querySelector('dialog[open]')||e.target===expression||e.target.tagName==='TEXTAREA'||e.target.tagName==='INPUT'||e.metaKey||e.ctrlKey||e.altKey)return;if(e.key==='Enter'&&e.target.tagName==='BUTTON')return;if(e.key==='Enter'||e.key==='='){e.preventDefault();calculate();}else if(e.key==='Escape')action('clear');else if(e.key==='Backspace'){e.preventDefault();action('back');}else if(/^[0-9+\-*/().,^x]$/.test(e.key)){e.preventDefault();insert(e.key);}});
// Clicking anywhere in the window (not in a field) gives it the keyboard, like the original page did.
on(root,'pointerdown',e=>{if(!e.target.closest('textarea,input,dialog'))queueMicrotask(()=>{if(!root.contains(document.activeElement)||document.activeElement===document.body)root.focus({preventScroll:true});});});
function renderSolution(r){const steps=r.steps.map((s,i)=>`<div class="step"><span class="step-index">${i+1}</span><div><div class="step-title">${esc(s.title)}</div><div class="step-math">${mathHTML(s.tex)}</div></div></div>`).join('');$('steps').innerHTML=steps+`<div class="result-card" data-testid="calc-result-card"><span>ОТВЕТ</span><strong>${r.resultTex?mathHTML(r.resultTex):esc(r.answer)}</strong>${r.detail?'<p>'+esc(r.detail)+'</p>':''}</div>`;$('steps').scrollTop=0;}
function calculate(){try{const r=solve(expression.value,angle);result=r;let ans=r.answer;if(r.kind==='expression'&&!ans.includes('/')){const n=Number(ans.replace(',','.'));if(Number.isFinite(n)&&Math.abs(n)<1e12)ans=n.toLocaleString('ru-RU',{maximumFractionDigits:10});}$('answer').textContent=ans;$('answer').classList.toggle('compact',ans.length>12);$('answerDetail').textContent=r.detail;renderSolution(r);done=true;history.unshift({input:r.input,answer:r.answer,angle,science});history=history.slice(0,50);$('footerStatus').textContent=(science?'Научный':'Обычный')+' режим · '+(r.kind==='equation'?'Уравнение решено':'Вычислено');preview();return r;}catch(e){result=null;done=false;$('answer').textContent='Проверьте ввод';$('answer').classList.add('compact');$('answerDetail').textContent='';$('steps').innerHTML='<div class="error" data-testid="calc-error">'+esc(e.message||'Не удалось вычислить выражение.')+'</div>';return{error:e.message};}}
for(const b of root.querySelectorAll('[data-example]'))b.onclick=()=>{setMode(true);expression.value=b.dataset.example;expression.setSelectionRange(expression.value.length,expression.value.length);calculate();};
$('copyButton').onclick=async()=>{if(!result){toast('Сначала вычислите выражение');return;}try{await navigator.clipboard.writeText(result.input+'\n\n'+result.steps.map((s,i)=>(i+1)+'. '+s.title+'\n'+s.tex).join('\n\n')+'\n\nОтвет: '+result.answer);toast('Решение скопировано');}catch{toast('Браузер не разрешил копирование');}};
// Dialogs open inside the window: a scrim over the app, the panel centred in it.
function openDialog(d){closeDialogs();d.show();root.classList.add('dialog-open');d.querySelector('.close-dialog')?.focus({preventScroll:true});}
function closeDialogs(){for(const d of root.querySelectorAll('dialog[open]'))d.close();}
for(const d of root.querySelectorAll('dialog'))on(d,'close',()=>{if(!root.querySelector('dialog[open]')){root.classList.remove('dialog-open');if(!destroyed)root.focus({preventScroll:true});}});
for(const b of root.querySelectorAll('.close-dialog'))b.onclick=()=>b.closest('dialog').close();$('scrim').onclick=closeDialogs;
// The solution panel: beside the keypad on wide windows, a panel over it on narrow ones (phones).
function showSolution(open){root.classList.toggle('show-solution',open);onSolutionToggle?.(open);}
$('solutionBack').onclick=()=>showSolution(false);
const help=()=>openDialog($('helpDialog'));function showHistory(){const list=$('historyList');list.innerHTML='';if(!history.length)list.innerHTML='<p class="muted">Здесь появятся ваши вычисления.</p>';for(const h of history){const b=document.createElement('button');b.className='history-item';const span=document.createElement('span');span.textContent=h.input;const strong=document.createElement('strong');strong.textContent=h.answer;b.append(span,strong);b.onclick=()=>{angle=h.angle;$('angleMode').textContent=angle;setMode(h.science);expression.value=h.input;expression.setSelectionRange(expression.value.length,expression.value.length);calculate();$('historyDialog').close();};list.append(b);}}const openHistory=()=>{showHistory();openDialog($('historyDialog'));};$('clearHistory').onclick=()=>{history=[];showHistory();};
// Science mode on short windows: functions and digits share one area (tabs) instead of scrolling.
function setPad(digits){root.classList.toggle('pad-digits',digits);$('padDigits').classList.toggle('selected',digits);$('padFunctions').classList.toggle('selected',!digits);$('padDigits').setAttribute('aria-selected',digits);$('padFunctions').setAttribute('aria-selected',!digits);}
$('padFunctions').onclick=()=>setPad(false);$('padDigits').onclick=()=>setPad(true);setPad(false);
const calc=$('calculator');
const pads=[$('keypad'),$('scienceKeys')];const overflows=el=>el.offsetParent!==null&&el.scrollHeight>el.clientHeight+1;
// The lowest level at which nothing in the keypad column overflows (keys never shrink below their touch-safe minimum).
function fit(){if(destroyed)return;for(let level=0;level<=3;level++){root.dataset.fit=String(level);if(!overflows(calc)&&!pads.some(overflows))break;}}
const ro=new ResizeObserver(()=>fit());ro.observe(root);
let photoURL=null,photoFile=null,worker=null,ocrBusy=false,photoVersion=0;const photo=$('photoPreview'),photoBox=photo.parentElement;let cropStart=null,cropRect=null,selection=null;
$('cameraButton').onclick=$('cameraMini').onclick=()=>$('cameraInput').click();$('galleryButton').onclick=$('galleryMini').onclick=()=>$('galleryInput').click();
async function loadPhoto(file){if(!file)return;if(!file.type.startsWith('image/')){toast('Выберите файл изображения');return;}if(file.size>25*1024*1024){toast('Выберите фото размером до 25 МБ');return;}photoVersion++;photoFile=file;if(photoURL)URL.revokeObjectURL(photoURL);photoURL=URL.createObjectURL(file);photo.src=photoURL;$('ocrText').value='';$('ocrStatus').textContent='Выделите нужное уравнение или нажмите «Распознать». Фото обрабатывается на вашем устройстве.';cropRect=null;selection?.remove();selection=null;photoBox.classList.remove('cropping');$('cropButton').textContent='Выделить уравнение';$('recognizeButton').disabled=false;$('cropButton').disabled=false;openDialog($('photoDialog'));}
// A file that claims to be an image but cannot be decoded.
on(photo,'error',()=>{if(!photoFile)return;photoFile=null;$('recognizeButton').disabled=true;$('cropButton').disabled=true;$('ocrStatus').textContent='Не удалось открыть изображение. Выберите другое фото.';});
for(const id of ['cameraInput','galleryInput'])$(id).onchange=e=>{loadPhoto(e.target.files[0]);e.target.value='';};
$('cropButton').onclick=()=>{const crop=photoBox.classList.toggle('cropping');$('cropButton').textContent=crop?'Выделите область на фото':'Выделить уравнение';};
function point(e){const r=photo.getBoundingClientRect();return{x:Math.max(0,Math.min(r.width,e.clientX-r.left)),y:Math.max(0,Math.min(r.height,e.clientY-r.top)),width:r.width,height:r.height};}
on(photoBox,'pointerdown',e=>{if(!photoBox.classList.contains('cropping')||ocrBusy)return;e.preventDefault();photoBox.setPointerCapture(e.pointerId);cropStart=point(e);selection?.remove();selection=document.createElement('div');selection.className='crop-selection';photoBox.append(selection);});
on(photoBox,'pointermove',e=>{if(!cropStart)return;const p=point(e),r=photo.getBoundingClientRect(),box=photoBox.getBoundingClientRect();cropRect={x:Math.min(p.x,cropStart.x),y:Math.min(p.y,cropStart.y),w:Math.abs(p.x-cropStart.x),h:Math.abs(p.y-cropStart.y),width:p.width,height:p.height};Object.assign(selection.style,{left:(cropRect.x+r.left-box.left)+'px',top:(cropRect.y+r.top-box.top)+'px',width:cropRect.w+'px',height:cropRect.h+'px'});});
on(photoBox,'pointerup',()=>{if(cropStart){cropStart=null;photoBox.classList.remove('cropping');$('cropButton').textContent='Изменить выделение';if(!cropRect||cropRect.w<12||cropRect.h<12){cropRect=null;selection?.remove();}else $('ocrStatus').textContent='Область выделена. Нажмите «Распознать».';}});
// Like the original, plus a capital X right after a digit ("2X"), which Tesseract often reads for the variable.
function cleanOCR(s){return normalize(s).replace(/[хХ]/g,'x').replace(/\bX\b/g,'x').replace(/(\d)X(?![A-Za-z])/g,'$1x').replace(/[“”‘’]/g,'').replace(/[|]/g,'1').replace(/\r/g,'').trim();}
const ocrURL=new URL(ocrBase,document.baseURI);
async function recognize(){if(!photoFile||ocrBusy)return;ocrBusy=true;const version=photoVersion;$('recognizeButton').disabled=true;$('cropButton').disabled=true;$('usePhoto').disabled=true;$('ocrProgress').hidden=false;$('ocrProgress').value=0;$('ocrStatus').textContent='Подготавливаем распознавание…';try{await photo.decode();const canvas=document.createElement('canvas');const scale=photo.naturalWidth/photo.getBoundingClientRect().width;const c=cropRect?{x:cropRect.x*scale,y:cropRect.y*scale,w:cropRect.w*scale,h:cropRect.h*scale}:{x:0,y:0,w:photo.naturalWidth,h:photo.naturalHeight};const factor=Math.min(2,2400/Math.max(c.w,c.h));canvas.width=Math.max(1,Math.round(c.w*factor));canvas.height=Math.max(1,Math.round(c.h*factor));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(photo,c.x,c.y,c.w,c.h,0,0,canvas.width,canvas.height);const img=ctx.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<img.data.length;i+=4){const gray=.299*img.data[i]+.587*img.data[i+1]+.114*img.data[i+2];const v=Math.min(255,Math.max(0,(gray-128)*1.3+128));img.data[i]=img.data[i+1]=img.data[i+2]=v;}ctx.putImageData(img,0,0);if(!worker){const {createWorker}=await import('tesseract.js');const w=await createWorker('eng',1,{workerPath:new URL('worker.min.js',ocrURL).href,corePath:ocrURL.href,langPath:ocrURL.href,workerBlobURL:false,logger:m=>{if(!ocrBusy||destroyed)return;$('ocrProgress').value=m.progress||0;$('ocrStatus').textContent=m.status==='recognizing text'?'Распознаём текст… '+Math.round((m.progress||0)*100)+'%':'Загружаем модуль распознавания…';}});if(destroyed){await w.terminate().catch(()=>{});return;}worker=w;await worker.setParameters({tessedit_pageseg_mode:'6',preserve_interword_spaces:'1'});}const {data}=await worker.recognize(canvas);if(version!==photoVersion||destroyed)return;const lines=data.text.split('\n').map(cleanOCR).filter(Boolean);const candidates=lines.filter(l=>/[0-9]/.test(l)&&/[=+*/^\-]/.test(l));$('ocrText').value=(candidates.length?candidates:lines).join('\n');$('ocrStatus').textContent=$('ocrText').value?'Текст распознан. Проверьте знаки, степени и дроби, оставьте одно уравнение.':'Текст не удалось прочитать. Попробуйте выделить уравнение, сделать более чёткое фото или введите его вручную.';$('ocrProgress').value=1;}catch(e){if(destroyed)return;$('ocrStatus').textContent='Не удалось распознать фото. Попробуйте другое изображение или введите уравнение вручную.';console.error('OCR:',e);if(worker){await worker.terminate().catch(()=>{});worker=null;}}finally{ocrBusy=false;if(!destroyed){$('recognizeButton').disabled=!photoFile;$('cropButton').disabled=!photoFile;$('usePhoto').disabled=false;}}}
$('recognizeButton').onclick=recognize;$('usePhoto').onclick=()=>{const s=$('ocrText').value.trim();if(!s){toast('Распознайте фото или введите уравнение');return;}if(s.split('\n').filter(l=>l.trim()).length>1){toast('Оставьте в поле одно уравнение');return;}setMode(true);expression.value=s;expression.setSelectionRange(s.length,s.length);calculate();$('photoDialog').close();showSolution(true);};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'solve_calculator_expression',title:'Решить выражение',description:'Ввести выражение или уравнение в калькулятор, вычислить и показать шаги решения.',inputSchema:{type:'object',properties:{expression:{type:'string',maxLength:500},angle:{type:'string',enum:['RAD','DEG']}},required:['expression'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.expression!=='string'||input.expression.length>500||Object.keys(input).some(k=>!['expression','angle'].includes(k))||input.angle&&!['RAD','DEG'].includes(input.angle))throw Error('Некорректный ввод');angle=input.angle||'RAD';$('angleMode').textContent=angle;setMode(true);expression.value=input.expression;expression.setSelectionRange(expression.value.length,expression.value.length);const r=calculate();if(r.error)throw Error(r.error);return{answer:r.answer,detail:r.detail,steps:r.steps};}},{signal:ac.signal})).catch(()=>{});}catch{}}
expression.setSelectionRange(expression.value.length,expression.value.length);setMode(false);calculate();
return{
  openHistory,openHelp:help,
  toggleSolution(){showSolution(!root.classList.contains('show-solution'));},
  focus(){root.focus({preventScroll:true});},
  destroy(){destroyed=true;ac.abort();ro.disconnect();clearTimeout(toastTimer);closeDialogs();if(photoURL)URL.revokeObjectURL(photoURL);if(worker){worker.terminate().catch(()=>{});worker=null;}root.innerHTML='';root.classList.remove('vxc','science','pad-digits','show-solution','dialog-open');delete root.dataset.fit;},
};
}
